Publish exsisting ports upon startup
rancher-sandbox/rancher-desktop-agent pull request #12
Opened 2022-09-20 15:39 UTC by Nino-K

Signed-off-by: Nino Kodabande <nkodabande@suse.com>

2022-09-20 22:03 UTC, mook-as requested changes

2022-09-20 22:03 UTC, mook-as commented on pkg/docker/events.go
> +		log.Errorf("initializing exsisting container port mappings failed: %v", err)
```suggestion
		log.Errorf("initializing existing container port mappings failed: %v", err)
```
Or a better rephrase:
```suggestion
		log.Errorf("failed to initialize existing container port mappings: %v", err)
```

2022-09-20 22:03 UTC, mook-as commented on pkg/docker/events.go
> +		Filters: filters.NewArgs(filters.Arg("status", "running")),
I thought `All` was used to show stopped containers (and therefore setting it to false was the same as filtering by `status=running`)?

2022-09-20 23:26 UTC, Nino-K commented on pkg/docker/events.go
> +		Filters: filters.NewArgs(filters.Arg("status", "running")),
You are right, it's not necessary.

2022-09-20 23:46 UTC, mook-as approved these changes

2022-09-21 16:15 UTC, Nino-K commented
https://github.com/rancher-sandbox/rancher-desktop/issues/2677

2022-09-21 19:08 UTC, merged