Manually register the port mapping for k8s API
rancher-sandbox/rancher-desktop-agent pull request #59
Opened 2024-05-06 19:00 UTC by Nino-K

This will send a port mapping event to Rancher-Desktop wsl-proxy for port 6443. This manual registration of k8s API port only applies when kubernetes along with wsl-integration are enabled.

Fixes: https://github.com/rancher-sandbox/rancher-desktop/issues/6831

2024-05-06 20:37 UTC, mook-as requested changes
I'm not entirely happy that this logic is going in `-agent` instead of the JS side, especially since we still don't have any documentation on what feature is active/working in which circumstance.

2024-05-06 20:37 UTC, mook-as commented on cmd/rancher-desktop-guestagent/main.go
> +		// following conditions:
It's unclear if this is describe a set of conditions that must _all_ be reached, or if we want _any_ condition to be reached.  Please rephrase.

2024-05-06 20:37 UTC, mook-as commented on cmd/rancher-desktop-guestagent/main.go
> +				k8sServiceListenerIP.Equal(net.IPv4(127, 0, 0, 1))) { //nolint:gomnd,mnd // IPv4 addr localhost
See other PR: whitelisting `net.IPv4` seems like a better fix.

2024-05-07 17:28 UTC, Nino-K commented
> I'm not entirely happy that this logic is going in `-agent` instead of the JS side, especially since we still don't have any documentation on what feature is active/working in which circumstance.

I disagree, I think this logic does belong in the agent and the JS should only provide the configuration for this feature. However, it is worth noting that currently there is a disconnect in [where we forward](https://github.com/rancher-sandbox/rancher-desktop/blob/6bd509de6a4a3d5059c6df0b487c1c229236a4ec/pkg/rancher-desktop/backend/wsl.ts#L123) the port to the host for K8s API, and where we emit a port mapping event for wsl-integration. Given that these two events (port forwarding for host and wsl-distro for k8s API) are independent of each other, however,  I agree with the fact that this should be documented to elaborate this behavior further. I will create a follow-up PR to explain this in the README docs.

2024-05-07 19:14 UTC, mook-as approved these changes

2024-05-07 19:14 UTC, merged